version: '2'

services:
  postgres:
    image: postgres:13-alpine
    ports:
    - 5432:5432
    environment:
      DB_HOST: pgsql
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
